import { probeSchema } from "@octo/run-host";
import type { Capabilities } from "@octo/editor";
import PlatformEditor from "@/app/components/PlatformEditor";
import UserMenu from "@/app/components/UserMenu";

/**
 * Bookmarkable editor route for a saved integration: `/platform/i/<id>` opens that
 * integration in the editor (loaded client-side by IntegrationLoader).
 * `/platform/new` opens a fresh document.
 *
 * The capability schema is generated by the `octo` binary (`octo schema`, cached
 * on first probe) and injected into the client editor; null when no runner is
 * configured, in which case the editor falls back to its empty bundled JSON.
 */
export default async function IntegrationEditorPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const capabilities = (await probeSchema()) as Capabilities | null;
  return (
    <PlatformEditor
      integrationId={id}
      userMenu={<UserMenu />}
      capabilities={capabilities}
    />
  );
}
