{{- define "octo.postgres.secretData" -}}
postgres-username: {{ .Values.postgres.auth.username | quote }}
postgres-password: {{ .Values.postgres.auth.password | quote }}
postgres-database: {{ .Values.postgres.auth.database | quote }}
{{- end }}
{{- include "octo-common.secret" (dict
      "root" $
      "component" "postgres"
      "stringData" (include "octo.postgres.secretData" .)) }}
