{{- include "octo-common.statefulset" (dict
      "root" $
      "component" "postgres"
      "replicas" 1
      "serviceName" (include "octo.postgres.serviceName" .)
      "containers" (include "octo-common.container" (dict
        "name" "postgres"
        "image" (printf "%s:%s" .Values.postgres.image.repository .Values.postgres.image.tag)
        "pullPolicy" .Values.postgres.image.pullPolicy
        "ports" (list (dict "name" "postgres" "containerPort" 5432))
        "env" (include "octo.postgres.env" .)
        "readinessProbe" (dict
          "exec" (dict "command" (list "pg_isready" "-U" .Values.postgres.auth.username "-d" .Values.postgres.auth.database))
          "initialDelaySeconds" 5
          "periodSeconds" 5)
        "volumeMounts" (list (dict "name" "data" "mountPath" "/var/lib/postgresql/data"))
        "resources" .Values.postgres.resources))
      "volumeClaimTemplates" (include "octo.postgres.volumeClaimTemplates" .)) }}
