apiVersion: v1
kind: Secret
metadata:
  name: {{ include "octo.postgres.serviceName" . }}
  labels:
    {{- include "octo.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  postgres-username: {{ .Values.postgres.auth.username | quote }}
  postgres-password: {{ .Values.postgres.auth.password | quote }}
  postgres-database: {{ .Values.postgres.auth.database | quote }}
