// Package openapi holds the platform API contract the api services module
// expects, as an OpenAPI 3.1 document, and serves it to whoever needs to read it.
//
// The document is HAND-WRITTEN, unlike the orchestrator's and the log
// aggregator's, and the difference is not a shortcut. Those two are generated by
// swaggo from handler annotations, describing an API their own code serves. This
// one describes an API this repo does not implement and never will: the runtime
// is the client, and the server is somebody else's. There are no handlers to
// annotate. The alternatives are worse — dummy Go handlers written purely to feed
// the generator are fiction that will rot, and reflecting a type set into schemas
// gives components with no paths, no status codes, no examples, and none of the
// prose an implementer actually needs.
//
// YAML rather than the orchestrator's JSON for the same reason: this file is
// edited and read by people, so it needs comments, multi-line descriptions and
// examples. The orchestrator's JSON is machine output, where none of that applies.
//
// Because generation cannot check us, tests do. routes_test.go asserts the
// document's paths are exactly the route table the module calls, and
// discovery_test.go asserts the discovery schema's property names match the Go
// structs field for field. That is the same move services/k8s already makes for
// the Redis wire contract, and it fails with a message saying what drifted rather
// than that something did.
//
// The package is data only: no init, no registration, no build tag. It is
// compiled into every octo binary, so `octo openapi` hands a user the contract
// their runtime actually speaks rather than whatever the website last published.
package openapi
