import { probeSchema } from "@octo/run-host";
import type { Capabilities } from "@octo/editor";
import StandaloneEditor from "./components/StandaloneEditor";

/**
 * `/` opens a fresh flow; `/?file=<id>` opens a saved one (the editor loads it
 * from the local-disk filesystem). The id round-trips through the query so a
 * reload reopens the same flow.
 *
 * The capability schema is generated by the bundled `octo` binary (`octo schema`,
 * cached on first probe) and injected into the client editor; when no runner is
 * configured this resolves to null and the editor falls back to its bundled JSON.
 */
export default async function Home({
  searchParams,
}: {
  searchParams: Promise<{ file?: string }>;
}) {
  const { file } = await searchParams;
  const capabilities = (await probeSchema()) as Capabilities | null;
  return <StandaloneEditor file={file} capabilities={capabilities} />;
}
