{{- include "octo-common.deployment" (dict
      "root" $
      "component" "orchestrator"
      "replicas" .Values.orchestrator.replicas
      "serviceAccountName" (include "octo-common.serviceAccountName" (dict "root" $ "component" "orchestrator"))
      "containers" (include "octo-common.container" (dict
        "root" $
        "component" "orchestrator"
        "name" "orchestrator"
        "image" (include "octo-common.image" (dict "root" $ "repo" .Values.orchestrator.repository))
        "pullPolicy" .Values.image.pullPolicy
        "ports" (list (dict "containerPort" .Values.orchestrator.service.port))
        "env" (include "octo.orchestrator.env" .)
        "readinessProbe" (dict
          "httpGet" (dict "path" "/healthz" "port" .Values.orchestrator.service.port)
          "initialDelaySeconds" 3
          "periodSeconds" 10)))) }}
