# The octo Helm release, owned by Terraform. Apply this right after publishing
# images (Cloud Build on a tag, or `task images:push` + `task helm:push`):
#
#   terraform -chdir=deploy/terraform/release apply -var image_tag=v0.1.1
#
# It pulls the target tag onto the node (fresh token, via octo-pull over SSH),
# then installs/upgrades the chart through the Helm provider. A changed image_tag
# rolls the Deployments. Prereqs: deploy/terraform/k3s applied, and
# `task deploy:kubeconfig` has produced the kubeconfig.

locals {
  image_base = "${var.region}-docker.pkg.dev/${var.project_id}/${var.repository_id}"
  secret_id  = coalesce(var.secret_id, "${var.instance_name}-postgres")
  kubeconfig = var.kubeconfig != "" ? var.kubeconfig : "${path.module}/../k3s/kubeconfig.yaml"
}

# Operator access token for pulling the OCI chart from Artifact Registry.
data "google_client_config" "current" {}

# Postgres password generated by the k3s root and stored in Secret Manager.
data "google_secret_manager_secret_version" "postgres" {
  secret  = local.secret_id
  project = var.project_id
}

# Pull the target tag onto the node with a fresh token so the chart's pods
# (imagePullPolicy IfNotPresent) find the images locally. Re-runs when the tag
# changes; the chart install/upgrade depends on it.
resource "null_resource" "pull_images" {
  triggers = {
    image_tag = var.image_tag
  }

  provisioner "local-exec" {
    interpreter = ["bash", "-c"]
    command     = "gcloud compute ssh ${var.instance_name} --zone ${var.zone} --project ${var.project_id} --command 'sudo octo-pull ${var.image_tag}'"
  }
}

module "octo" {
  source = "../modules/helm-release"

  image_base        = local.image_base
  chart_version     = var.chart_version
  image_tag         = var.image_tag
  registry_password = data.google_client_config.current.access_token
  domain            = var.domain
  postgres_password = data.google_secret_manager_secret_version.postgres.secret_data
  cluster_issuer    = var.cluster_issuer

  depends_on = [null_resource.pull_images]
}
