import { describe, it, expect, beforeEach } from "vitest";
import { Box } from "lucide-react";
import {
  CAPABILITIES,
  setCapabilities,
  getBlockSpec,
  getConnectorSpec,
  getSourceSpec,
  listBlocks,
  listConnectors,
  listSources,
  resolveIcon,
  type Capabilities,
} from "./index";

// A minimal but complete schema exercising the injection path (one block, one
// connector with a source). The real, full catalogue is generated by the runtime
// (`octo schema`) and validated there; the editor only needs to prove it renders
// whatever schema it is handed and tolerates the empty fallback.
const sample: Capabilities = {
  blocks: [
    {
      type: "demo",
      label: "Demo",
      category: "processor",
      icon: "Wand2",
      description: "A demo block.",
      fields: [{ name: "value", label: "Value", type: "cel", required: true }],
    },
  ],
  connectors: [
    {
      type: "democon",
      label: "Demo Connector",
      icon: "Globe",
      settings: [],
      sources: [{ type: "demosrc", label: "Demo Source", icon: "Globe", fields: [] }],
    },
  ],
};

// This file tests the empty-fallback + injection seam itself, so it opts out of
// the global test fixture (see vitest.setup.ts) and starts each test from the
// real, empty bundled fallback. The global afterEach still resets afterwards.
beforeEach(() => setCapabilities(null));

describe("capability schema", () => {
  it("ships an empty, well-formed fallback (real schema comes from the runtime)", () => {
    expect(CAPABILITIES.blocks).toEqual([]);
    expect(CAPABILITIES.connectors).toEqual([]);
  });

  it("keeps every accessor safe on the empty fallback (no runner, no crash)", () => {
    expect(listBlocks()).toEqual([]);
    expect(listConnectors()).toEqual([]);
    expect(listSources()).toEqual([]);
    expect(getBlockSpec("anything")).toBeUndefined();
    expect(getConnectorSpec("anything")).toBeUndefined();
    expect(getSourceSpec("anything", "anything")).toBeUndefined();
  });

  it("reflects an injected schema through every accessor", () => {
    setCapabilities(sample);
    expect(listBlocks().map((b) => b.type)).toEqual(["demo"]);
    expect(getBlockSpec("demo")?.label).toBe("Demo");
    expect(getConnectorSpec("democon")?.label).toBe("Demo Connector");
    const sources = listSources();
    expect(sources).toHaveLength(1);
    expect(sources[0]).toMatchObject({
      connector: "democon",
      connectorLabel: "Demo Connector",
    });
    expect(getSourceSpec("democon", "demosrc")?.label).toBe("Demo Source");
  });

  it("restores the empty fallback when injected with null", () => {
    setCapabilities(sample);
    expect(listBlocks()).toHaveLength(1);
    setCapabilities(null);
    expect(listBlocks()).toEqual([]);
  });

  it("resolves known icon names to components and unknown names to a fallback box", () => {
    expect(resolveIcon("Wand2")).not.toBe(Box);
    expect(resolveIcon("Slack")).not.toBe(Box);
    expect(resolveIcon("does-not-exist")).toBe(Box);
  });
});
