name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: runtime/go.work
      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b "$(go env GOPATH)/bin"
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - run: task release-check
      - run: task build
